// <auto-generated />
using System;
using FincoreCoreMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FincoreCoreMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FincoreCoreMvc.Models.AccountMasters", b =>
                {
                    b.Property<int>("Account_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Account_Id"));

                    b.Property<string>("Account_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Account_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Account_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_By")
                        .HasColumnType("int");

                    b.Property<byte>("Is_Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Modified_By")
                        .HasColumnType("int");

                    b.HasKey("Account_Id");

                    b.HasIndex("Created_By");

                    b.HasIndex("Modified_By");

                    b.ToTable("AccountMasters");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.BudgetLines", b =>
                {
                    b.Property<int>("Budget_Line_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Budget_Line_Id"));

                    b.Property<decimal>("Allocated_Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Budget_Category_Id")
                        .HasColumnType("int");

                    b.Property<int>("Budget_Id")
                        .HasColumnType("int");

                    b.Property<int?>("BudgetsCategoriesBudget_Category_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_By")
                        .HasColumnType("int");

                    b.Property<byte>("Is_Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Modified_By")
                        .HasColumnType("int");

                    b.Property<decimal?>("Utilized_Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Budget_Line_Id");

                    b.HasIndex("Budget_Category_Id");

                    b.HasIndex("Budget_Id");

                    b.HasIndex("BudgetsCategoriesBudget_Category_Id");

                    b.HasIndex("Created_By");

                    b.HasIndex("Modified_By");

                    b.ToTable("BudgetLines");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Budgets", b =>
                {
                    b.Property<int>("Budget_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Budget_Id"));

                    b.Property<decimal>("Budget_Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Budget_Category_Id")
                        .HasColumnType("int");

                    b.Property<string>("Budget_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Budget_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Financial_Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Is_Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Modified_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Start_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Budget_Id");

                    b.HasIndex("Budget_Category_Id");

                    b.HasIndex("Created_By");

                    b.HasIndex("Modified_By");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.BudgetsCategories", b =>
                {
                    b.Property<int>("Budget_Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Budget_Category_Id"));

                    b.Property<string>("Categor_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_By")
                        .HasColumnType("int");

                    b.Property<int>("Department_Id")
                        .HasColumnType("int");

                    b.Property<byte>("Is_Active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Modified_By")
                        .HasColumnType("int");

                    b.HasKey("Budget_Category_Id");

                    b.HasIndex("Created_By");

                    b.HasIndex("Department_Id");

                    b.HasIndex("Modified_By");

                    b.ToTable("BudgetsCategories");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.CapexRequests", b =>
                {
                    b.Property<int>("Capex_Request_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Capex_Request_Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Approval_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Approved_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Approved_By")
                        .HasColumnType("int");

                    b.Property<int>("Budget_Line_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Department_Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Requested_By")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Capex_Request_Id");

                    b.HasIndex("Approved_By");

                    b.HasIndex("Budget_Line_Id");

                    b.HasIndex("Department_Id");

                    b.HasIndex("Requested_By");

                    b.ToTable("CapexRequests");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Department", b =>
                {
                    b.Property<int>("department_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("department_id"));

                    b.Property<int>("branch_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("department_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("is_active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("department_id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.ExpenseClaims", b =>
                {
                    b.Property<int>("Expense_Claim_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Expense_Claim_Id"));

                    b.Property<string>("Approval_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Approved_By")
                        .HasColumnType("int");

                    b.Property<int>("Claim_By")
                        .HasColumnType("int");

                    b.Property<string>("Claim_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Expense_Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Expense_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Expense_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Opex_Request_Id")
                        .HasColumnType("int");

                    b.HasKey("Expense_Claim_Id");

                    b.HasIndex("Approved_By");

                    b.HasIndex("Claim_By");

                    b.HasIndex("Opex_Request_Id");

                    b.ToTable("ExpenseClaims");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.OpexRequests", b =>
                {
                    b.Property<int>("Opex_Request_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Opex_Request_Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Approval_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Approved_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Approved_By")
                        .HasColumnType("int");

                    b.Property<int>("Budget_Line_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Requested_By")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Opex_Request_Id");

                    b.HasIndex("Approved_By");

                    b.HasIndex("Budget_Line_Id");

                    b.HasIndex("Requested_By");

                    b.ToTable("OpexRequests");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Permissions", b =>
                {
                    b.Property<int>("permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permission_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<byte>("is_active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<string>("permission_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("permission_id");

                    b.HasIndex("role_id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Role", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("role_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("isActive")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("role_id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("is_active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("user_id");

                    b.HasIndex("role_id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.AccountMasters", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("Modified_By")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.BudgetLines", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.BudgetsCategories", "BudgetCategory")
                        .WithMany()
                        .HasForeignKey("Budget_Category_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.Budgets", "Budget")
                        .WithMany("BudgetLines")
                        .HasForeignKey("Budget_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.BudgetsCategories", null)
                        .WithMany("BudgetLines")
                        .HasForeignKey("BudgetsCategoriesBudget_Category_Id");

                    b.HasOne("FincoreCoreMvc.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("Modified_By")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Budget");

                    b.Navigation("BudgetCategory");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Budgets", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.BudgetsCategories", "BudgetCategory")
                        .WithMany()
                        .HasForeignKey("Budget_Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("Modified_By")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BudgetCategory");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.BudgetsCategories", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Department_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("Modified_By")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Department");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.CapexRequests", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("Approved_By")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FincoreCoreMvc.Models.BudgetLines", "BudgetLine")
                        .WithMany("CapexRequests")
                        .HasForeignKey("Budget_Line_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Department_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("Requested_By")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("BudgetLine");

                    b.Navigation("Department");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.ExpenseClaims", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("Approved_By")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FincoreCoreMvc.Models.User", "ClaimByUser")
                        .WithMany()
                        .HasForeignKey("Claim_By")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.OpexRequests", "OpexRequest")
                        .WithMany("ExpenseClaims")
                        .HasForeignKey("Opex_Request_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("ClaimByUser");

                    b.Navigation("OpexRequest");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.OpexRequests", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("Approved_By")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FincoreCoreMvc.Models.BudgetLines", "BudgetLine")
                        .WithMany("OpexRequests")
                        .HasForeignKey("Budget_Line_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("Requested_By")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("BudgetLine");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Permissions", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.Role", "role")
                        .WithMany("permissions")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.User", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.Role", "role")
                        .WithMany("users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.BudgetLines", b =>
                {
                    b.Navigation("CapexRequests");

                    b.Navigation("OpexRequests");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Budgets", b =>
                {
                    b.Navigation("BudgetLines");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.BudgetsCategories", b =>
                {
                    b.Navigation("BudgetLines");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.OpexRequests", b =>
                {
                    b.Navigation("ExpenseClaims");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Role", b =>
                {
                    b.Navigation("permissions");

                    b.Navigation("users");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.State", b =>
                {
                    b.Navigation("cities");
                });
#pragma warning restore 612, 618
        }
    }
}
