// <auto-generated />
using System;
using FincoreCoreMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FincoreCoreMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FincoreCoreMvc.Models.City", b =>
                {
                    b.Property<int>("city_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("city_id"));

                    b.Property<string>("city_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<byte?>("is_active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<int?>("state_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("city_id");

                    b.HasIndex("state_id");

                    b.HasIndex("user_id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Company", b =>
                {
                    b.Property<int>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("company_id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("city_id")
                        .HasColumnType("int");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("country_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gstin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("is_active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<string>("pan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("company_id");

                    b.HasIndex("city_id");

                    b.HasIndex("country_id");

                    b.HasIndex("user_id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Country", b =>
                {
                    b.Property<int>("country_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("country_id"));

                    b.Property<int?>("country_code")
                        .HasColumnType("int");

                    b.Property<string>("country_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<byte?>("is_active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("country_id");

                    b.HasIndex("user_id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Department", b =>
                {
                    b.Property<int>("department_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("department_id"));

                    b.Property<int>("branch_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("department_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("is_active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("department_id");

                    b.HasIndex("user_id");

                    b.ToTable("department");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"));

                    b.Property<int>("company_id")
                        .HasColumnType("int");

                    b.Property<int>("company_id1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<int>("department_id1")
                        .HasColumnType("int");

                    b.Property<int>("designation_id")
                        .HasColumnType("int");

                    b.Property<int>("designationrole_id")
                        .HasColumnType("int");

                    b.Property<byte?>("is_active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("joining_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<int?>("reporting_manager_id")
                        .HasColumnType("int")
                        .HasColumnName("Reporting Manager");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id1")
                        .HasColumnType("int");

                    b.HasKey("employee_id");

                    b.HasIndex("company_id1");

                    b.HasIndex("department_id1");

                    b.HasIndex("designationrole_id");

                    b.HasIndex("reporting_manager_id");

                    b.HasIndex("user_id1");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Permissions", b =>
                {
                    b.Property<int>("permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permission_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<byte?>("is_active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<string>("permission_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("role_id")
                        .HasColumnType("int");

                    b.HasKey("permission_id");

                    b.HasIndex("role_id");

                    b.ToTable("permission");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Role", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("role_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("isActive")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<string>("role_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("role_id");

                    b.ToTable("role");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.State", b =>
                {
                    b.Property<int>("state_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("state_id"));

                    b.Property<int?>("country_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<byte?>("is_active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<string>("state_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("state_id");

                    b.HasIndex("country_id");

                    b.HasIndex("user_id");

                    b.ToTable("State");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("is_active")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("role_id")
                        .HasColumnType("int");

                    b.Property<int>("role_id1")
                        .HasColumnType("int");

                    b.HasKey("user_id");

                    b.HasIndex("role_id1");

                    b.ToTable("user");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.City", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.State", "state")
                        .WithMany("cities")
                        .HasForeignKey("state_id");

                    b.HasOne("FincoreCoreMvc.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("state");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Company", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.City", "city")
                        .WithMany()
                        .HasForeignKey("city_id");

                    b.HasOne("FincoreCoreMvc.Models.Country", null)
                        .WithMany("companies")
                        .HasForeignKey("country_id");

                    b.HasOne("FincoreCoreMvc.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Country", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Department", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Employee", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.Company", "company")
                        .WithMany()
                        .HasForeignKey("company_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("department_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.Role", "designation")
                        .WithMany()
                        .HasForeignKey("designationrole_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincoreCoreMvc.Models.Employee", "reporting_manager")
                        .WithMany()
                        .HasForeignKey("reporting_manager_id");

                    b.HasOne("FincoreCoreMvc.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("company");

                    b.Navigation("department");

                    b.Navigation("designation");

                    b.Navigation("reporting_manager");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Permissions", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.Role", "role")
                        .WithMany("permissions")
                        .HasForeignKey("role_id");

                    b.Navigation("role");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.State", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.Country", "country")
                        .WithMany("state")
                        .HasForeignKey("country_id");

                    b.HasOne("FincoreCoreMvc.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.User", b =>
                {
                    b.HasOne("FincoreCoreMvc.Models.Role", "role")
                        .WithMany("users")
                        .HasForeignKey("role_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Country", b =>
                {
                    b.Navigation("companies");

                    b.Navigation("state");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.Role", b =>
                {
                    b.Navigation("permissions");

                    b.Navigation("users");
                });

            modelBuilder.Entity("FincoreCoreMvc.Models.State", b =>
                {
                    b.Navigation("cities");
                });
#pragma warning restore 612, 618
        }
    }
}
